trigger:
  - master
pr:
  - master
 
jobs:
  - job:
    displayName: 'Check line endings'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          FILES=`git diff -C --diff-filter=ACM --name-only origin/$(Build.SourceBranch) origin/$(System.PullRequest.TargetBranch)`
          if [ x"$FILES" = x ] ; then
            echo "There are no files to check for line endings."
          else
            BAD_FILES=
            for file in $FILES ; do
              echo "Checking file: '$file'"
              type=`file -b $file`
              case "$type" in
                *empty*)
                  echo "Empty file: '$file'"
                  ;;
                *text*)
                  set nocasematch
                  lcFile=`echo $file | tr 'upper' 'lower'`
                  case "$lcFile" in
                    *.bat | *.cmd)
                      case "$type" in
                        *CRLF*)
                          echo "Good windows script: '$file' type: '$type'"
                          ;;
                        *)
                          echo "ERROR - should have CRLF line terminators: '$file' type: '$type'"
                          BAD_FILES="$BAD_FILES $file"
                          ;;
                      esac
                      ;;
                    *)
                      case "$type" in
                        *CR*)
                          echo "ERROR - should have LF line terminators: '$file' type: '$type'"
                          BAD_FILES="$BAD_FILES $file"
                          ;;
                        *)
                          echo "Good text file: '$file' type: '$type'"
                          ;;
                      esac
                      ;;
                  esac
                  ;;
                *)
                  echo "Non-text file: '$file' type: '$type'"
                  ;;
              esac
            done
            HASHES='###################################'
            if [ x"$badfiles" != x ] ; then
              echo "$HASHES"
              echo "The following files were modified and have incorrect line endings:"
              for file in $FILES ; do
                echo "$file"
              done
              echo "$HASHES"
              exit 1
            else
              echo "Checking for added trailing whitespace..."
              git config core.whitespace blank-at-eof,blank-at-eol,cr-at-eol,space-before-tab
              WHITESPACE_ERRORS=`git diff --check origin/$(Build.SourceBranch) origin/$(System.PullRequest.TargetBranch) --`
              if [ x"$WHITESPACE_ERRORS" = x ] ; then
                echo "All modified files appear to have correct line endings."
              else
                echo "$HASHES"
                echo "$WHITESPACE_ERRORS"
                echo "$HASHES"
                exit 1
              fi
            fi
          fi
        displayName: 'Check added, changed or modified files'
